### ISSUE TITLE
無法開啟批次檔??!

### ISSUE THREAD

**Issue by pajamas110** [trexminer/T-Rex#1057]
![快照-1](https://user-images.githubusercontent.com/32599721/152846701-acbac34d-0ccb-420a-92a7-457d773b355d.jpg)

**Comment by GrzegorzWo** [comment]
From google translate:
Topic: "Unable to open batch file"
Content: "t-rex.exe is not an internal or external command, executable program or batch file". "Please press any key to continue".

I think here you should just press any key. ;-)

But seriously: 
1) your system language is set o Chinese, that's why you see messages in Chinese.
2) this is typical behaviour when you open batch file with administration privileges. If using admin rights, you need to type full path to exe file inside *.bat . As I can see, in your case it is:
`C:\Users\Yu\Desktop\t-rex-0.25.2-win\t-rex.exe -a ethash -o stratum+tcp://eth.2miners.....` etc.
