### ISSUE TITLE
Hi! 3060 LHR error on ETH+RVN 

### ISSUE THREAD

**Issue by Leandrocabralsantana** [trexminer/T-Rex#1155]
Hi! How are you.
I'm currently trying to mine with my 3060 LHR card. I did it with lolminer and nicehash, but I'm currently trying to make dual ETH+RVN and learn how to use T-rex.
I changed with the info from different pools but I keep getting this message.

 t-rex -a ethash --dual-algo autolykos2 -o stratum+tcp://eu1.ethermine.org:4444 -u 0x3185bc55edC1352D249fdb5b5511f74d4466C545 -p x -w rig0 --url2 stratum+tcp://pool.woolypooly.com:3100 --user2 0x3185bc55edC1352D249fdb5b5511f74d4466C545.rig0 --pass2 x
pause
![image](https://user-images.githubusercontent.com/100740901/157053395-8586e903-e86e-43e0-8e30-fbc4e86ab5bf.png)

How can I make it work? Thanks!

**Comment by trexminer** [comment]
RVN uses `kawpow` algorithm, yet you're setting `--dual-algo autolykos2`. Also, you've specified ETH wallet address in `--user2` instead of RVN one.
At the same time the screenshot says you're connecting to 2miners pool to mine ETH, but the command line you provided uses ethermine, not sure what's up with that?
I'd recommend to double check your config.

**Comment by Leandrocabralsantana** [comment]
Hi! I was doing my baby steps with T-rex and mining in general. I did it and it's working really fine in my 3060 LHR. I checked the configuration and yeah, it had a lot of errors hahaha.
I solved it, thanks man!
