### ISSUE TITLE
Invalid Shares Issue

### ISSUE THREAD

**Issue by JordanRaphael** [trexminer/T-Rex#181]
So I'm running 2x3070 (one Eagle and one Aorus Master) and I noticed a weird behaviour, after I OC'd my cards, every invalid shared that I was getting was coming from my Aorus Master. So I tried again with no OC, I had 0 invalid shares. Then I OC'd only the Eagle, but again the T-rex was showing that my Aorus Master was having the Invalid shares.

**Comment by trexminer** [comment]
What version of T-Rex are you running?

**Comment by JordanRaphael** [comment]
t-rex-0.19.9-win-cuda11.1

**Comment by trexminer** [comment]
When you look at the miner console, how do you know which card is which? Does it display "Eagle" and "Aorus" words in the cards names? I'm asking because the order in which CUDA detects GPUs does not always match MSI Afterburner ordering.
You can change the ordering scheme the miner is using by running it with `--ab-indexing` to match Afterburner.

**Comment by JordanRaphael** [comment]
I will try this indexing and I will update you if anything changes, thanks.
