### ISSUE TITLE
HTTP API - cant access on other PC's in LAN

### ISSUE THREAD

**Issue by photonminer** [trexminer/T-Rex#192]
updated from 19.9 to 19.10, and subsequently was unable to access the HTTP API using my typical address on other PC's within the wireless network, however I could access the API from the mining rig.  

am I missing something?

**Comment by souserig** [comment]
@photonminer does your typical address contain the hostname of the mining rig? Or does it contain the IP of the mining rig?

I'm experiencing the same issue after upgrading to 19.10. Cant access the webpage on http://<hostname>:4067 as I previously could from my cellphone whilst on the same network.
Connecting via IP (e.g. http://192.168.0.22:4067) works fine, but is not ideal as previously it was accesible on hostname.

I also tested by passing in the --api-bind-http arg with value '0.0.0.0:4067', which seems to be the default anyway, didn't have desired effect.

**Comment by photonminer** [comment]
> @photonminer does your typical address contain the hostname of the mining rig? Or does it contain the IP of the mining rig?
> 
> I'm experiencing the same issue after upgrading to 19.10. Cant access the webpage on http://hostname:4067 as I previously could from my cellphone whilst on the same network.
> Connecting via IP (e.g. http://192.168.0.22:4067) works fine, but is not ideal as previously it was accessible on hostname.
> 
> I also tested by passing in the --api-bind-http arg with value '0.0.0.0:4067', which seems to be the default anyway, didn't have desired effect.

bear with me im new to this, so I do not understand the difference. When the program starts it says navigate to this address  which i assume is my ip and port like this - http://<IP>:<port>/<handler_name>

**Comment by Unlifate** [comment]
Can't agree to you. I am not having this issue. My host is localhost. And for me both ways are working: 127.0.0.1 and localhost. So hostname aswell as ip are working. I am using the config-file startup variant and 0.19.10 on windows 10. My config setting is:
` "api-bind-http": "0.0.0.0:4067"`

**Comment by souserig** [comment]
@Unlifate I can also access it from the machine running trex. Locally I can access it via hostname, ip as well as loopback ip (127.0.0.1).

I understood the question to relate to accessing the webpage from another device on the same network, e.g. cellphone connected to same network via wifi or another computer on the same network.

I just tested again and proved my initial result wrong. I can in fact access the webpage, served by trex on the mining machine, from another device on the same network via hostname as well as IP.

When I experienced the issue, it must have failed because of DNS lookup not correctly resolving my mining machine hostname to its IP assigned by the router. So it definitely is still working in v0.19.10.

**Comment by photonminer** [comment]
@Unlifate so this morning I reinstalled 19.10.

when I start the program it tells me “navigate to 127.0.0.1:4067/trex” which I can access from the local miner. However trying from another computer in the network I get a “ERR_CONNECTION_REFUSED” timeout 

Before updating the address was 10.0.0.1:4067/trex and I had none of these issues

When I look up my IP in my wireless properties it says 10.0.0.169 but when I try to use this address nothing happens
