### ISSUE TITLE
Feature Request: VRAM temperature in Web UI

### ISSUE THREAD

**Issue by relevante** [trexminer/T-Rex#196]
My GPU core temps on 3090 are never an issue, but I'm constantly concerned about VRAM. Would be great to be able to monitor this remotely.

**Comment by ec3566** [comment]
RTX 3090 does not have a VRAM sensor, GDDR6X only has a memory junction temperature, which is not indicative of actual memory temperature. It is hotspot temperature, and can be significantly higher than actual memory temperature, or somewhat close. Actual temperature can be 80C, but junction may report 110C. 3090's memory modules are also on both sides of the PCB, with the back half getting essentially zero cooling,, due to it dumping heat into a backplate and not a heatsink. It is not possible to get accurate temperature readings through software.

**Comment by relevante** [comment]
Sorry for the lack of specificity. The memory junction temperature is actually what I was referring to. I understand there may be some uncertainty with the measurement source, but I’ve found it to be a useful metric that seems to correlate logically with efforts I’ve made to cool the cards, and specifically the backplate.

Definitely not a huge issue at this point though. I have things pretty much stabilized at this point and fortunately don’t spend much time monitoring at this point anyway since things are working well.
