### ISSUE TITLE
Display Memory T-Junction Temp for GDDR6X supported platforms.

### ISSUE THREAD

**Issue by oderbang** [trexminer/T-Rex#236]
As the comment suggests 30series cards seem to be reliant on memory temp rather than core temp so could mem temp be used in place or along side the core temp?

**Comment by paolocampitelli** [comment]
Please add this feature since it is very important, more than gpu temperature which is not stressed by mining.
In my rtx 3080, gpu temperature is 45 degrees meanwhile vram temperature is 90 degrees. Please also add the possibility to limit trex if temperature is > number set by the user, it could be very useful to prevent damages to our gpus.

Thanks

**Comment by joshuajaharwood** [comment]
Hotspot temperature for <3080s would also be very useful. HWInfo can report this.

**Comment by trexminer** [comment]
This is available since version 0.21.0
