### ISSUE TITLE
Virus Detected In This Version

### ISSUE THREAD

**Issue by storm5510** [trexminer/T-Rex#30]
Windows 10 v1903 Defender reports virus Behavior.Win32/Generic.KL!ml is in this release.

**Comment by Urgo** [comment]
Not saying there isn't a virus in it, but I can say that windows defender finds viruses in pretty much every piece of mining software and many wallets too.  It's pretty stupid. They've gone out and blacklisted crypto so anyone wanting to be involved basically has to just ignore windows defender because of all the false positives.

Use it at your own risk of course, but there probably isn't a virus?  That said don't sue me I'm not the author just a user :)

**Comment by moo-duck** [comment]
> Windows 10 v1903 Defender reports virus Behavior.Win32/Generic.KL!ml is in this release.

are you drunk?

**Comment by storm5510** [comment]
> 
> 
> > Windows 10 v1903 Defender reports virus Behavior.Win32/Generic.KL!ml is in this release.
> 
> are you drunk?

**No! are you?**

> 
> 
> Not saying there isn't a virus in it, but I can say that windows defender finds viruses in pretty much every piece of mining software and many wallets too. It's pretty stupid. They've gone out and blacklisted crypto so anyone wanting to be involved basically has to just ignore windows defender because of all the false positives.
> 
> Use it at your own risk of course, but there probably isn't a virus? That said don't sue me I'm not the author just a user :)

I suspected this may be the case. I simply wanted  someone here to verify.  There is an option in Defender's message to "Allow on this device."  Prior, I did a single-file scan on it.  No problem found.  
The warning appeared when I tried to start it.  The program was immediately deleted. I set the option to "allow" and there was no additional warning.

**Comment by trexminer** [comment]
We explained it in https://github.com/trexminer/T-Rex#antivirus-alerts
