### ISSUE TITLE
0.20.0 and 0.20.1 Blue Screen with new commands using admin mode

### ISSUE THREAD

**Issue by 93srvman** [trexminer/T-Rex#426]
Running both 0.20.0 and 0.20.1 versions on Windows I am trying to incorporate the new commands, example command line: 

###
E:\Mining\t-rex-latest\t-rex.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u #wallet address removed# -d 1 --pl 60 --mclock 1300 --cclock 502 -p x -w rig999
pause
###

Only the  "pl" setting takes effect with "mclock" and "cclock" saying they need admin access to set.  When I do right click "run as administrator" t-rex will start up, appear to take all the new commands but then the PC grinds to a halt and blue screens shortly thereafter.  This is repeatable.  

If it matters: I do have 2 GPU's in the system, but I'm just attempting to get this first working on the one as a test.  When sorted out I will definitely want to specify the settings (which will be different) on the second card as well.

**Comment by pdieppa** [comment]
Have you tried a different value for --cclock?

**Comment by markuznw** [comment]
That's for sure wrong values passed, mine is working completely fine on 2070s boxes
Try lowering values and see or check on web for "recommended" values for your card/s

**Comment by 93srvman** [comment]
Nice catch! I missed the "-" in front of the 502.    Working fine now, and running different settings for both cards.  This is a really sweet enhancement which removes the constant open/update settings within Afterburner for when switching between gaming/mining.

**Comment by pdieppa** [comment]
It's a great update for Windows users, but keep in mind there is a way to run MSI Afterburner from the command line and assigned any of the 5 profiles on demand. This is a nice feature because you can run that command when Windows boots up and makes sure your OCs are applied automatically. It's very useful for Windows installations that start mining automatically.

I use HiveOs and the platform manages its own overclocking.

**Comment by igoralebar** [comment]
close the issue if there's no issue

and also, overclocking with afterburner can hurt stability of mining, since it's applied constantly, instead of after miner has built the dag file

**Comment by gwongis88** [comment]
Is that true Igoralebar?  Anyone willing to 2nd that?  If so I will switch and start using it...  Thanks

**Comment by 93srvman** [comment]
PEBKAC Issue resolved.

**Comment by pdieppa** [comment]
In my experience, you always want to apply your OC setting BEFORE you start mining. You can't have GPUs drawing their maximum power until they finish with the DAG. That would burn my rig down. That's the reason why HiveOs applies the overclock settings as soon as an algo is selected.

Maybe is different for Windows.

**Comment by 93srvman** [comment]
I haven't noticed that in Windows.  When I first was figuring out the sweet spot for both cards it was complete settings tweaking on the fly (with Afterburner) while I let the miner run for a number shares/responses to get a feel for the speed vs. settings.  Regardless with the new setting capabilities it will all be set before hand now.

**Comment by igoralebar** [comment]
I my experience, I've had corrupt DAG that results in a bunch of invalid shares, when starting up miner with OC applied on the edge of stability.
While on the other hand, DAG built safely without overclock works without issues, with the same overclock applied right after building DAG.

**Comment by pdieppa** [comment]
So, a good question would be:

How is t-rex applying the OC setting? Before or after the DAG?
In my case, I have a bunch of GPUs, among those I have 6 5700XT. After OC is applied, they mine at 85-89 watts. Without OC, they draw close to 200 watts each. For me is critical I never let the GPUs either build the DAG or mine for any length of time, no matter how short it is at full power. I have a 1600 Watts power supply on that rig but the UPS is only rated at 1000 watts. Letting the cards mine at default would shut down the whole system since the UPS will shut off at overload.

Good technical tidbits back and forth!!!
I love to learn new things every day

**Comment by igoralebar** [comment]
Your case doesn't seems to be very common, so you probably should avoid saying something like "you always want to apply your OC setting BEFORE you start mining", when it's mainly derived from quirkiness of your setup.
In normal situation, it is better to have OC applied right after DAG is built, because it allows you to have higher mem OC without DAG corruption. And also, NVIDIA GPUs have power limit option, which is always applied at the start, so if in your case you had NVIDIA GPUs, small UPS wouldn't be an issue.
The default behavior of t-rex, I believe, is applying OC when DAG is built. I'm also not sure if t-rex is intended to be used with AMD cards at all, it even says right in the title "T-Rex NVIDIA GPU miner". You probably should look at teamredminer instead.

**Comment by pdieppa** [comment]
That's the reason why I said I have a bunch of GPUs, my other ones are Nvidia 3070s and 3060 Ti. . Yes I use TRM for OpenCL since t-rex is only for cuda based cards. My comment still stands for power management. It's not unique to me as everyone that mines has to deal with power usage. You mentioned power limits, are you saying that t-rex apply power limits when the program starts? Again, since I don't use Windows, I don't know how that works.

With HiveOs, if I don't set a Overclocking profile for the coin that I'm mining, my 3070 cards will use almost 260 watts each. The 3060 Ti cards will use almost 230 watts. Since I use t-rex for those, I have not seen any kind of power limit when they are working with the DAG or after. I must set the OC or the cards will run at their default setting. Now, both 3070s and 3060 Ti use about 50 watts each at idle and between 120 watts and 150 watts during mining. 

I will have to experiment with the new setting in t-rex to see how they behave. 
Thanks for your input, it's greatly appreciated. I'm done! :)

**Comment by igoralebar** [comment]
that's probably a handicap of mining on linux, under windows t-rex and other mining tools than have built-in oc features, apply overclock right after dag is built
maybe hiveos can interact with t-rex somehow and apply overclocks and power limits when necessary, I have no experience with it
there's also a sequential GPU utilization mode, so even if you had no power limit and low power OC was applied right after DAG, only one GPU at a time would be maxed out on power
