### ISSUE TITLE
Help needed miner shows epoch, block, difficulty only on start

### ISSUE THREAD

**Issue by gminadak** [trexminer/T-Rex#502]
Hello.
I started using T-Rex recently and I noticed that epoch, block, difficulty only shows at start on ethash.
Is there anyway to change this?
On octopus works fine.
Thank you. 

![IMG_20210610_150840~2](https://user-images.githubusercontent.com/45330594/121524477-081f1e80-ca00-11eb-8776-50384c642083.jpg)
![IMG_20210610_141908](https://user-images.githubusercontent.com/45330594/121524515-0fdec300-ca00-11eb-805b-360e385bd7b5.jpg)

**Comment by trexminer** [comment]
Perhaps binance pool doesn't push the block info, try another pool.

**Comment by gminadak** [comment]
> Perhaps binance pool doesn't push the block info, try another pool.

I can see the info with other mining software

**Comment by trexminer** [comment]
@gminadak could you show a screenshot of the said software please?

**Comment by gminadak** [comment]
@trexminer 

Sure

![IMG_20210613_193728~2](https://user-images.githubusercontent.com/45330594/121815546-b4bb0380-cc7f-11eb-80b7-856e6125599a.jpg)
![IMG_20210613_194129](https://user-images.githubusercontent.com/45330594/121815539-a967d800-cc7f-11eb-92db-c8d3d49a5e34.jpg)

**Comment by trexminer** [comment]
Ok, thanks. Those are "new job", not "new block" messages though. We don't display them as they are typically very frequent. Binance pool doesn't publish block numbers which is why you're not seeing "new block" messages (as opposed to those on your octopus screenshot).
You can run the miner with `--protocol-dump` to display "new job" messages but the miner will also print a lot of low-level stuff you probably aren't interested in.

**Comment by gminadak** [comment]
I really appreciate the information.
Thank you.
