### ISSUE TITLE
Compile error: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by Aurum420** [trexminer/T-Rex#57]
Cannot get T-Rex 15.6 to mine kawpow. It starts but never mines. I also have nvidia-toolkit installed. I've also tried rebooting. Also why won't it bind 4067 or 4068. My start script:
#!/bin/sh
./t-rex -a kawpow -o stratum+tcp://kawpow.usa.nicehash.com:3385 -u 37m4fy8zwnoXYEVsV4hs6YsNgeQ7iKKYuT.Rig_02

Linux Mint 19.3
Timestamp                           : Sat May 16 12:36:02 2020
Driver Version                      : 440.82
CUDA Version                        : 10.2
Attached GPUs                       : 1
GPU 00000000:01:00.0
Product Name                    : GeForce RTX 2080 Ti

![image](https://user-images.githubusercontent.com/60850550/82128635-764bd000-9771-11ea-9a8c-b09e7b998583.png)

**Comment by trexminer** [comment]
Which CUDA build of t-rex are you running? It's printed on the very first line of the log (not visible on the screenshot)

**Comment by Aurum420** [comment]
t-rex-0.15.7-linux-cuda10.0.tar.gz

**Comment by trexminer** [comment]
This is most likely due to either two or more CUDA versions installed in the system, one of which is older than 10.0 and the miner picking the older one by default (check the symlinks), OR the only CUDA installed in the system is older than 10.0.
In other words, the miner needs CUDA v10.0+ libraries to work with RTX cards.

**Comment by trexminer** [comment]
0.18.1 no longer requires the CUDA toolkit to be installed, so this issue should be fixed
