### ISSUE TITLE
GTX 1060 6GB - "not enough free memory to mine ethash at epoch 436"

### ISSUE THREAD

**Issue by hoakerk** [trexminer/T-Rex#598]
Any reason for this to happen?

![trex_error](https://user-images.githubusercontent.com/16647546/131178403-1d77a3d1-b28c-4117-b4da-2c2fe79afc9a.png)

RTX 3070 - OK
GTX 1060 6GB - NOK

Only these 2 GPUs are in the system.

Tried bunch of different configs without luck. No, I don't believe I need more then 32GB of virtual memory.
Small notice - in 100 attempts it did started up - twice - and mine for a few minutes.

**Comment by trexminer** [comment]
Because you specified `--extra-dag-epoch 0` the miner tries to fit both 1GB DAG for ZIL and 4GB+ DAG for ETH into the GPU memory, and since Windows also takes some VRAM for itself there isn't enough memory left for the miner.
You can either use Linux or remove `--extra-dag-epoch 0` at a cost of having to rebuild the DAG every time the pool switches from ZIL to ETH and back.
