### ISSUE TITLE
LHR mode Non reducing 

### ISSUE THREAD

**Issue by Teddymeyn** [trexminer/T-Rex#652]
While LHR mode getting detected there needs to be an options to run the mining with the same LHR mode

**Comment by lowzyyy** [comment]
That would be great or something like this: if miner is stable at some lhr-tune X, after some time try lhr-tune X+1.

Also i dont get it what is the ideal combination for LHR to not occur. I tried core clock from 1700 to 1000, memory from 750-900mhz but i always get LHR locked with 5 or 6 setting and i always back to lhr-tune 4 which i hate (only 81-82mhs @275w 3080 ti tuf)

**Comment by ZeddieXX** [comment]
Dang, I literally posted this issue right after yours, lol.

I would also like a way to stick to a LHR and keep it there instead of tuning down.  The GPU would be hashing at a set value for hours, then if I open a window or do something that would temporarily drop the hash rate down for a while, it would auto-tune down.  I would have to restart the miner to get it back to the right value again before I lock my rig.

Also, I have a 3080 ti that I just can't seem to get more than 76 MH/s, but auto-tune keeps thinking it's still LHR locked and keeps tuning down until it gets to LHR 1 and then I end up with 72 MH/s.  I rather hash at 76 MH/s than 72 MH/s if I can.  Oh, and it's not auto-tuning because LHR kicked in (it never goes lower than 76 MH/s).  It just auto-tunes even when it stays at 76 MH/s.  I can understand auto-tuning LHR when it goes from 76 to say 50 MH/s, but that's not the case.
