### ISSUE TITLE
new update with newest navaida driver halfed my hash rate  was 120 now its 54 on ergo 

### ISSUE THREAD

**Issue by RealStonerGamer** [trexminer/T-Rex#843]
new update with newest navaida driver halfed my hash rate  was 120 now its 54 on ergo

**Comment by trexminer** [comment]
Haha, better not to upgrade then :)

**Comment by xanten11** [comment]
wow a bit rude ...

**Comment by doramine** [comment]
agree not to upgrade lol
i lost some power at 0.24.x so i keep running on 0.23.2 lol

**Comment by trexminer** [comment]
@xanten11 why rude? NVIDIA keeps releasing new versions with all sorts of bugs, causing miner crashes, memory leaks and so on, so we have to constantly come up with various workarounds. Usually these bugs are fixed in later versions so there's no reason to spend time trying to solve their issues unless they are still present after, say, a few months.
If your setup is stable and there's nothing in the new version that you can benefit from, why upgrade?

**Comment by xanten11** [comment]
> @xanten11 why rude? NVIDIA keeps releasing new versions with all sorts of bugs, causing miner crashes, memory leaks and so on, so we have to constantly come up with various workarounds. Usually these bugs are fixed in later versions so there's no reason to spend time trying to solve their issues unless they are still present after, say, a few months. If your setup is stable and there's nothing in the new version that you can benefit from, why upgrade?

i understand that but the way you say it " Haha, better not to upgrade then :) "   that is rude

**Comment by trexminer** [comment]
Sorry, I didn't mean to offend you
