### ISSUE TITLE
Can intensity regulation work on the initialization of miners

### ISSUE THREAD

**Issue by q1398590q** [trexminer/T-Rex#86]
Computer is so laggy when miners start.

Thanks for adding.

**Comment by q1398590q** [comment]
When the ETH DAG is initializing, the system becomes very stuck, can the intensity of the initialization be adjusted?

**Comment by trexminer** [comment]
If you use the same GPU to drive the display and for mining, then the effect you're describing is expected. We can add optional delays and initialise DAG in chunks but that would be a low priority task because it only affects a few people especially given that the DAG generation only takes 10 seconds or so.

**Comment by q1398590q** [comment]
Thank you for your reply.
Although this only affects a few people, I have great computing power (about 10000 GPUs), which has a great impact on me. I hope you can add it as soon as possible. Thank you.

**Comment by trexminer** [comment]
I'm afraid this won't get implemented in the near future
